version: "3"
services:
  slack-nobiru-kun:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: slack-nobiru-kun-image
    container_name: slack-nobiru-kun
    tty: true
    env_file: ../.env
