version: "3"
services:
  slack-next-gen-platform-template:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: slack-next-gen-platform-template-image
    container_name: slack-next-gen-platform-template
    tty: true
    env_file: ../.env
